x

diff --git a/.github/workflows/external.yml b/.github/workflows/external.yml
--- a/.github/workflows/external.yml
+++ b/.github/workflows/external.yml
@@ -82,15 +82,12 @@ jobs:
     - name: Set DISPLAY variable
       run: echo "DISPLAY=:99" >> $GITHUB_ENV
 
-    # - name: Run wish command
-    #   run: wish -c "puts OK; exit"
-
-    - name: Check for wish
-      run: |
-        TMPDIR=${TMPDIR:-/tmp}
-        WORKSPACE=$(mktemp -d $TMPDIR/opp_env_test_XXXXXX)
-        opp_env run --install --no-build omnetpp-4.0 -w $WORKSPACE --init -c "which wish || echo 'wish not found'"
-        echo $DISPLAY
+    # - name: Check for wish
+    #   run: |
+    #     TMPDIR=${TMPDIR:-/tmp}
+    #     WORKSPACE=$(mktemp -d $TMPDIR/opp_env_test_XXXXXX)
+    #     opp_env run --install --no-build omnetpp-4.0 -w $WORKSPACE --init -c "which wish || echo 'wish not found'"
+    #     echo $DISPLAY
 
     - name: Run test
       working-directory: tests
