x

diff --git a/.github/workflows/external.yml b/.github/workflows/external.yml
--- a/.github/workflows/external.yml
+++ b/.github/workflows/external.yml
@@ -75,7 +75,7 @@ jobs:
       run: |
         TMPDIR=${TMPDIR:-/tmp}
         WORKSPACE=$(mktemp -d $TMPDIR/opp_env_test_XXXXXX)
-        opp_env run --install --no-build omnetpp-4.0 -w $WORKSPACE --init -c "which wish || echo 'wish not found' && ./configure"
+        opp_env run --install --no-build omnetpp-4.0 -w $WORKSPACE --init -c "which wish || echo 'wish not found'"
         echo $DISPLAY
 
     - name: Run test
