x

diff --git a/.github/workflows/external.yml b/.github/workflows/external.yml
--- a/.github/workflows/external.yml
+++ b/.github/workflows/external.yml
@@ -71,12 +71,12 @@ jobs:
       with:
         nix_path: nixpkgs=channel:nixos-unstable
 
-    # - name: Check for wish
-    #   run: |
-    #     TMPDIR=${TMPDIR:-/tmp}
-    #     WORKSPACE=$(mktemp -d $TMPDIR/opp_env_test_XXXXXX)
-    #     opp_env run --install --no-build omnetpp-4.0 -w $WORKSPACE --init -c "which wish || echo 'wish not found' && ./configure"
-    #     which wish || echo "wish not found"
+    - name: Check for wish
+      run: |
+        TMPDIR=${TMPDIR:-/tmp}
+        WORKSPACE=$(mktemp -d $TMPDIR/opp_env_test_XXXXXX)
+        opp_env run --install --no-build omnetpp-4.0 -w $WORKSPACE --init -c "which wish || echo 'wish not found' && ./configure"
+        echo $DISPLAY
 
     - name: Run test
       working-directory: tests
