x

diff --git a/.github/workflows/external.yml b/.github/workflows/external.yml
--- a/.github/workflows/external.yml
+++ b/.github/workflows/external.yml
@@ -47,78 +47,78 @@ jobs:
       outputs:
         matrix: ${{ steps.set-matrix.outputs.matrix }}
 
-  # smoketests:
-  #   needs: create-combinations
-  #   strategy:
-  #     fail-fast: false
-  #     matrix:
-  #       projects: ${{ fromJson(needs.create-combinations.outputs.matrix) }}
-  #   name: Smoke test ${{ matrix.projects }}
-  #   runs-on: ubuntu-latest
+  smoketests:
+    needs: create-combinations
+    strategy:
+      fail-fast: false
+      matrix:
+        projects: ${{ fromJson(needs.create-combinations.outputs.matrix) }}
+    name: Smoke test ${{ matrix.projects }}
+    runs-on: ubuntu-latest
 
-  #   steps:
-  #   - uses: actions/checkout@v4
+    steps:
+    - uses: actions/checkout@v4
 
-  #   - name: Set up Python
-  #     uses: actions/setup-python@v5
-  #     with:
-  #       python-version: "3.x"
+    - name: Set up Python
+      uses: actions/setup-python@v5
+      with:
+        python-version: "3.x"
 
-  #   - name: Install locally
-  #     run: python3 -m pip install -e .
+    - name: Install locally
+      run: python3 -m pip install -e .
 
-  #   - uses: cachix/install-nix-action@v30
-  #     with:
-  #       nix_path: nixpkgs=channel:nixos-unstable
+    - uses: cachix/install-nix-action@v30
+      with:
+        nix_path: nixpkgs=channel:nixos-unstable
 
-  #   - name: Install Xvfb
-  #     run: |
-  #       sudo apt-get update
-  #       sudo apt-get install -y xvfb
+    - name: Install Xvfb
+      run: |
+        sudo apt-get update
+        sudo apt-get install -y xvfb
 
-  #   - name: Start Xvfb
-  #     run: Xvfb :99 -screen 0 1024x768x24 &
+    - name: Start Xvfb
+      run: Xvfb :99 -screen 0 1024x768x24 &
 
-  #   - name: Set DISPLAY variable
-  #     run: echo "DISPLAY=:99" >> $GITHUB_ENV
+    - name: Set DISPLAY variable
+      run: echo "DISPLAY=:99" >> $GITHUB_ENV
 
-  #   # - name: Check for wish
-  #   #   run: |
-  #   #     TMPDIR=${TMPDIR:-/tmp}
-  #   #     WORKSPACE=$(mktemp -d $TMPDIR/opp_env_test_XXXXXX)
-  #   #     opp_env run --install --no-build omnetpp-4.0 -w $WORKSPACE --init -c "which wish || echo 'wish not found'"
-  #   #     echo $DISPLAY
+    # - name: Check for wish
+    #   run: |
+    #     TMPDIR=${TMPDIR:-/tmp}
+    #     WORKSPACE=$(mktemp -d $TMPDIR/opp_env_test_XXXXXX)
+    #     opp_env run --install --no-build omnetpp-4.0 -w $WORKSPACE --init -c "which wish || echo 'wish not found'"
+    #     echo $DISPLAY
 
-  #   - name: Run test
-  #     working-directory: tests
-  #     run: ./project_tester --workspace /tmp/${{ matrix.projects }} install ${{ matrix.projects }}
+    - name: Run test
+      working-directory: tests
+      run: ./project_tester --workspace /tmp/${{ matrix.projects }} install ${{ matrix.projects }}
 
-  #   - name: ldd
-  #     if: always()
-  #     working-directory: /tmp/${{ matrix.projects }}
-  #     run: |
-  #       cd omnetpp-6.1.0/samples/dyna
-  #       ldd dyna
+    - name: ldd
+      if: always()
+      working-directory: /tmp/${{ matrix.projects }}
+      run: |
+        cd omnetpp-6.1.0/samples/dyna
+        ldd dyna
 
-  #   - name: makefile.inc config.log
-  #     if: always()
-  #     working-directory: /tmp/${{ matrix.projects }}
-  #     run: |
-  #       cd omnetpp-6.1.0
-  #       cat Makefile.inc
-  #       echo '------------------------------'
-  #       cat config.log
+    - name: makefile.inc config.log
+      if: always()
+      working-directory: /tmp/${{ matrix.projects }}
+      run: |
+        cd omnetpp-6.1.0
+        cat Makefile.inc
+        echo '------------------------------'
+        cat config.log
 
-  #   - name: Show output
-  #     if: always()
-  #     run: |
-  #       echo "::group::Output"
-  #       cat tests/logs/${{ matrix.projects }}.out || echo '(no output)'
-  #       echo "::endgroup::"
+    - name: Show output
+      if: always()
+      run: |
+        echo "::group::Output"
+        cat tests/logs/${{ matrix.projects }}.out || echo '(no output)'
+        echo "::endgroup::"
 
-  #       echo "::group::Error"
-  #       cat tests/logs/${{ matrix.projects }}.err || echo '(no output)'
-  #       echo "::endgroup::"
+        echo "::group::Error"
+        cat tests/logs/${{ matrix.projects }}.err || echo '(no output)'
+        echo "::endgroup::"
 
   omnetpp61:
     name: Smoke test omnetpp
